### PR TITLE
Adds introduction to sinatra sample app

### PR DESCRIPTION
**Pull request by inf0rmer**

### CODE REVIEW

**Comment by baschtl** [comment]
+B

**Comment by inf0rmer** [comment]
I can't merge it (no commit rights to the repo) so go ahead and do it!

**Comment by baschtl** [comment]
@rwrede As I was not present yesterday, could you take a final look and merge this PR? Thanks.

**Comment by rwrede** [comment]
@inf0rmer looks good. Only thing, maybe also add the following route to the README including the `name` param:

```
- [http://localhost:4567/?name=RubyTuesdays](http://localhost:4567/?name=RubyTuesdays)
```

**Comment by rwrede** [comment]
@inf0rmer I will ask someone to give you commit rights for the Repo.

**Comment by fmasuhr** [comment]
@rwrede currently @baschtl is team owner here and is able to add people
i already did that for this time.

**Comment by rwrede** [comment]
Ah cool. So @baschtl can you add @inf0rmer then?

**Comment by baschtl** [comment]
@fmasuhr No, I cannot: “Only organization owners can send invitations.” Bruno is not part of the Babbel organization on Github I guess. Hence, I cannot add him. ;-)

**Comment by fmasuhr** [comment]
@baschtl i was not aware of that. so i added him as collaborator for this repo ;)

**Pull request merged**
